<?php
session_start();
//unset($_SESSION["user_id"]);
//unset($_SESSION["name"]);
//unset($_SESSION["username"]);
//unset($_SESSION["shopping_cart"]);
session_unset();
header("Location:index.php");
?>